# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptiondate', models.DateField(verbose_name='Дата прийому')),
                ('cabinetno', models.IntegerField(blank=True, null=True, verbose_name='Кабінет')),
                ('periodcure', models.CharField(blank=True, max_length=30, verbose_name='Період лікування')),
                ('prescriptmedicine', models.CharField(blank=True, max_length=50, verbose_name='Призначення ліків')),
                ('symptoms', models.CharField(blank=True, max_length=100, verbose_name='Симптоми')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вага')),
                ('pressure', models.CharField(blank=True, max_length=30, verbose_name='Тиск')),
                ('analysis', models.CharField(blank=True, max_length=100, verbose_name='Аналізи та результати')),
                ('startdiagnosis', models.CharField(blank=True, max_length=100, verbose_name='Попередній діагноз')),
                ('enddiagnosis', models.CharField(blank=True, max_length=100, verbose_name='Остаточний діагноз')),
                ('recepttimestart', models.DateTimeField(default=datetime.datetime.now, verbose_name='Час прийому з')),
                ('recepttimeend', models.DateTimeField(default=datetime.datetime.now, verbose_name='Час прийому по')),
            ],
            options={
                'verbose_name_plural': 'Амбулаторні карти',
                'verbose_name': 'Амбулаторна карта',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(verbose_name='День тиждня')),
                ('recepttimestart', models.DateTimeField(blank=True, null=True, verbose_name='Час прийому з')),
                ('recepttimeend', models.DateTimeField(blank=True, null=True, verbose_name='Час прийому по')),
            ],
            options={
                'verbose_name': 'Розклад фахівця',
                'verbose_name_plural': 'Розклад персонала',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(verbose_name='День тиждня')),
                ('receptiontime', models.DateTimeField(verbose_name='Час прийому')),
            ],
            options={
                'verbose_name': 'Розклад детально',
                'verbose_name_plural': 'Розклад детально',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=30, verbose_name="И'мя")),
                ('middlename', models.CharField(blank=True, default='', max_length=30, verbose_name='По батькові')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('address', models.CharField(blank=True, max_length=80, verbose_name='Адреса')),
                ('workplace', models.CharField(blank=True, max_length=50, verbose_name='Місце роботи')),
                ('cardno', models.CharField(max_length=10, unique=True, verbose_name='Номер карти')),
            ],
            options={
                'verbose_name': 'Паціент',
                'verbose_name_plural': 'Паціенти',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=30, verbose_name="И'мя")),
                ('middlename', models.CharField(blank=True, default='', max_length=30, verbose_name='По батькові')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('cabinetno', models.IntegerField(verbose_name='Кабінет')),
            ],
            options={
                'verbose_name': 'Фахівець',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': 'Спеціальності',
                'verbose_name': 'Спеціальність',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, default='', max_length=30, verbose_name='По батькові')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('icq', models.CharField(blank=True, max_length=32, verbose_name='ICQ')),
                ('skype', models.CharField(blank=True, max_length=32, verbose_name='Skype')),
                ('patientid', models.IntegerField(blank=True, null=True, verbose_name='Код пацієнта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'permissions': (('login_to_site', 'Вхід до сайту'),),
                'verbose_name_plural': 'Профілі користувачей',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulat.Speciality', verbose_name='Спеціальність'),
        ),
        migrations.AddField(
            model_name='curriculumdet',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulat.Personnel', verbose_name='Фахівець'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulat.Personnel', verbose_name='Фахівець'),
        ),
        migrations.AddField(
            model_name='ambcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulat.Patient', verbose_name='Паціент'),
        ),
        migrations.AddField(
            model_name='ambcard',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulat.Personnel', verbose_name='Фахівець'),
        ),
        migrations.AlterUniqueTogether(
            name='ambcard',
            unique_together=set([('personnel', 'receptiondate', 'recepttimestart')]),
        ),
    ]
